### ISSUE TITLE
Questions about uploading tracking result files

### ISSUE THREAD

**Issue by Azong-HQU** [votchallenge/toolkit#106]
Hello, when I use the "vot pack xxx" command to compress the tracking results and submit the files to the system for performance evaluation, but the system raises this error, how can I solve this problem?

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/concurrent/futures/process.py", line 101, in _python_exit
    thread_wakeup.wakeup()
  File "/opt/conda/lib/python3.7/concurrent/futures/process.py", line 89, in wakeup
    self._writer.send_bytes(b"")
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 183, in send_bytes
    self._check_closed()
  File "/opt/conda/lib/python3.7/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
Traceback (most recent call last):
  File "/home/deploy/opt/latest/proj_thiai_codalab/tmp/codalab/tmpUCyaDP/run/program/evaluate.py", line 195, in 
    results = json.load(open(report_path, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/deploy/opt/latest/proj_thiai_codalab/tmp/codalab/tmpUCyaDP/run/input/res/analysis/analysis/results.json'

**Comment by lukacu** [comment]
I have no idea, since the code layout does not look like the toolkit. The "../run/program/evaluate.py" is some custom code, it tries to open some kind of report. But as I have said, this is not a stack trace of the toolkit.
