### ISSUE TITLE
execute test on a sequance WITH gui executed yeild AttributeError

### ISSUE THREAD

**Issue by barnoy1** [votchallenge/toolkit#110]
execute test on a sequance WITH gui executed yeild AttributeError: 'FigureCanvasTkAgg' object has no attribute 'set_window_title'

## setup

versions:
vot-trax                  4.0.1
vot-toolkit               0.6.4

## steps to reproduce on vs2023 stack:

1. running vot initalize and evaluate on vots2023 stack
```python
vot initialize --workspace tracker_ws vots2023
cd tracker_ws
vot evaluate --workspace . NCCPython
```
2. execute test on animal sequance without gui executed without errors
```python
vot test -s /home/ron/repo/vot-toolkit/tracker_ws/sequences/animal NCCPython
```

Generating dummy sequence
Obtaining runtime for tracker NCCPython
Initializing tracker
/home/ron/repo/vot-toolkit/integration/python/vot.py
@@TRAX:hello "trax.name=" "trax.family=" "trax.multiobject=1" "trax.image=path;" "trax.region=rectangle;" "trax.description=" "trax.version=4" "vot=python" "trax.channels=color;" 
@@TRAX:initialize "802.0000,246.0000,48.0000,25.0000" 
@@TRAX:frame "file:///home/ron/repo/vot-toolkit/tracker_ws/sequences/animal/color/00000001.jpg" 
@@TRAX:state "802.0000,246.0000,48.0000,25.0000" 
Processing frame 1/99
@@TRAX:frame "file:///home/ron/repo/vot-toolkit/tracker_ws/sequences/animal/color/00000002.jpg" 
@@TRAX:state "807.0000,247.0000,48.0000,25.0000" 

@@TRAX:frame "file:///home/ron/repo/vot-toolkit/tracker_ws/sequences/animal/color/00000098.jpg" 
@@TRAX:state "0.0000,0.0000,0.0000,0.0000" 
Processing frame 98/99
@@TRAX:frame "file:///home/ron/repo/vot-toolkit/tracker_ws/sequences/animal/color/00000099.jpg" 
@@TRAX:state "791.0000,65.0000,48.0000,25.0000" 
Processing frame 99/99
@@TRAX:frame "file:///home/ron/repo/vot-toolkit/tracker_ws/sequences/animal/color/00000100.jpg" 
@@TRAX:state "811.0000,69.0000,48.0000,25.0000" 
Stopping tracker
@@TRAX:quit 
Test concluded successfuly

2. execute test on animal sequance WITH gui executed yeild AttributeError: 'FigureCanvasTkAgg' object has no attribute 'set_window_title'
```python
vot test -g -s /home/ron/repo/vot-toolkit/tracker_ws/sequences/animal NCCPython 
```

Generating dummy sequence
Obtaining runtime for tracker NCCPython
'FigureCanvasTkAgg' object has no attribute 'set_window_title'
Traceback (most recent call last):
  File "/home/ron/repo/vot-toolkit/venv/lib/python3.11/site-packages/vot/utilities/cli.py", line 439, in main
    do_test(args)
  File "/home/ron/repo/vot-toolkit/venv/lib/python3.11/site-packages/vot/utilities/cli.py", line 113, in do_test
    figure.canvas.set_window_title('VOT Test')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FigureCanvasTkAgg' object has no attribute 'set_window_title'

**Comment by lukacu** [comment]
Thank you for this report, it seems that set title method is not very standard. Since figure title is not a crucial thing, you can comment the line, but we will try to make this more robust in the next version. On which OS are you?

**Comment by barnoy1** [comment]
hi @lukacu, thanks for the reply, 

I'm running on ubuntu 

```
Linux COMPUTER 5.15.0-78-generic #85~20.04.1-Ubuntu SMP Mon Jul 17 09:42:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

```

I marked off the line you suggested. 
```python
# figure.canvas.set_window_title('VOT Test')
```

Now it works just fine. 
I understand that this is an easy fix (the exposoure of this issue is pretty high since it comes directly from using the cli ).
 

Thanks.

**Comment by lukacu** [comment]
Yes, strangely enough, it does not happen with all installations, otherwise I would not have put this into the code. But it will be fixed soon officially.
