### ISSUE TITLE
report problem:can not report to HTML format results

### ISSUE THREAD

**Issue by tanglin00** [votchallenge/toolkit#116]
when i try to report the results to html format, there is indexerror:invalid index to scalar variable. Please help me slove this problem.
vot report --workspace ~/VOTTrackEval/vot2019-test NCC --format html
                      |                                         |   0% [00:00<?]invalid index to scalar variable.
Traceback (most recent call last):
  File "/home/workstation2/anaconda3/lib/python3.9/site-packages/vot_toolkit-0.7.0-py3.9.egg/vot/utilities/cli.py", line 540, in main
    do_report(args)
  File "/home/workstation2/anaconda3/lib/python3.9/site-packages/vot_toolkit-0.7.0-py3.9.egg/vot/utilities/cli.py", line 394, in do_report
    generate_document(workspace, trackers, config.format, name, config.sequences, config.experiments)
  File "/home/workstation2/anaconda3/lib/python3.9/site-packages/vot_toolkit-0.7.0-py3.9.egg/vot/report/__init__.py", line 759, in generate_document
    merge_tree(future.result(), reports)
  File "/home/workstation2/anaconda3/lib/python3.9/site-packages/vot_toolkit-0.7.0-py3.9.egg/vot/report/__init__.py", line 611, in generate
    items[experiment.identifier] = future.result()
  File "/home/workstation2/anaconda3/lib/python3.9/site-packages/vot_toolkit-0.7.0-py3.9.egg/vot/report/__init__.py", line 645, in perexperiment
    table = extract_measures_table(trackers, {experiment: results})
  File "/home/workstation2/anaconda3/lib/python3.9/site-packages/vot_toolkit-0.7.0-py3.9.egg/vot/report/common.py", line 63, in extract_measures_table
    table_data[tracker].append(values[i] if not values is None else None)
IndexError: invalid index to scalar variable.

**Comment by lukacu** [comment]
Just to clarify, all you did is run default evaluation for a NCC tracker that you have evaluated? No config change?

**Comment by lukacu** [comment]
I have found the problem and corrected it.

**Comment by tanglin00** [comment]
Sorry to bother you again. After downloading and running the code again, I encountered another issue while running the analysis code: No such file or directory.Looking forward to your reply.
vot report --workspace ~/tl/VOTTrackEval/test NCC --format html
                      |                                         |   0% [00:00<?][Errno 2] No such file or directory: '/home/workstation2/anaconda3/lib/python3.9/site-packages/vot_toolkit-0.7.0-py3.9.egg/vot/report/pure.css'
Traceback (most recent call last):
  File "/home/workstation2/anaconda3/lib/python3.9/site-packages/vot_toolkit-0.7.0-py3.9.egg/vot/utilities/cli.py", line 540, in main
    do_report(args)
  File "/home/workstation2/anaconda3/lib/python3.9/site-packages/vot_toolkit-0.7.0-py3.9.egg/vot/utilities/cli.py", line 394, in do_report
    generate_document(workspace, trackers, config.format, name, config.sequences, config.experiments)
  File "/home/workstation2/anaconda3/lib/python3.9/site-packages/vot_toolkit-0.7.0-py3.9.egg/vot/report/__init__.py", line 785, in generate_document
    generate_html_document(trackers, workspace.dataset, reports, report_storage)
  File "/home/workstation2/anaconda3/lib/python3.9/site-packages/vot_toolkit-0.7.0-py3.9.egg/vot/report/html.py", line 118, in generate_html_document
    add_style("pure.css", linked)
  File "/home/workstation2/anaconda3/lib/python3.9/site-packages/vot_toolkit-0.7.0-py3.9.egg/vot/report/html.py", line 99, in add_style
    style(read_resource(name))
  File "/home/workstation2/anaconda3/lib/python3.9/site-packages/vot_toolkit-0.7.0-py3.9.egg/vot/report/common.py", line 13, in read_resource
    with open(path, "r") as filehandle:
FileNotFoundError: [Errno 2] No such file or directory: '/home/workstation2/anaconda3/lib/python3.9/site-packages/vot_toolkit-0.7.0-py3.9.egg/vot/report/pure.css'

**Comment by lukacu** [comment]
Yes, found that as well a few minutes ago when I was making a new release. Some resources did not get packaged correctly after recent refactoring. Should be fixed now.
