### ISSUE TITLE
About 'vot analysis 'ERROR

### ISSUE THREAD

**Issue by deepbrainme** [votchallenge/toolkit#16]
(d3s) adminer@Robot:~/AAAA/Trackers/VOTBenchmarks/VOT2020$ vot analysis --workspace ~/AAAA/Trackers/VOTBenchmarks/VOT2020 --name D3S --format pdf
Checking for new version
No module named 'vot.analysis.document'
Traceback (most recent call last):
  File "/home/adminer/software/miniconda3/envs/d3s/lib/python3.7/site-packages/vot/utilities/cli.py", line 371, in main
    do_analysis(args, logger)
  File "/home/adminer/software/miniconda3/envs/d3s/lib/python3.7/site-packages/vot/utilities/cli.py", line 186, in do_analysis
    from vot.analysis.document import generate_json_document, generate_latex_document, generate_html_document
ModuleNotFoundError: No module named 'vot.analysis.document'

I have evaluated my tracker on vot2020,it is fine . However when I analysis my trackers,ERROR occured. Would you help me ?

**Comment by lukacu** [comment]
This issue is because the package exists, but is not installed. It is fixed in dev branch and if you use the toolkit without installation. We plan to merge the dev branch soon.

**Comment by ferumchrome** [comment]
Hi, I got the same error for vot2017. I tried to pip install the dev branch, but it gives me another error:

vot analysis --workspace /home/ferumchrome/Desktop/SiamDW/py-vot-toolkit/vot-workspace2017 --name sesiamfc_ip38 --format json
Checking for new version
'NoneType' object has no attribute 'rfind'
Traceback (most recent call last):
  File "/home/ferumchrome/anaconda3/envs/pytorch15/lib/python3.7/site-packages/vot/utilities/cli.py", line 366, in main
    do_analysis(args, logger)
  File "/home/ferumchrome/anaconda3/envs/pytorch15/lib/python3.7/site-packages/vot/utilities/cli.py", line 188, in do_analysis
    workspace = Workspace.load(config.workspace)
  File "/home/ferumchrome/anaconda3/envs/pytorch15/lib/python3.7/site-packages/vot/workspace.py", line 251, in load
    return Workspace(directory, **config)
  File "/home/ferumchrome/anaconda3/envs/pytorch15/lib/python3.7/site-packages/vot/workspace.py", line 256, in __init__
    super().__init__(**kwargs)
  File "/home/ferumchrome/anaconda3/envs/pytorch15/lib/python3.7/site-packages/vot/utilities/attributes.py", line 193, in __init__
    super().__setattr__(aname, afield.coerce(avalue, {"parent": self}))
  File "/home/ferumchrome/anaconda3/envs/pytorch15/lib/python3.7/site-packages/vot/workspace.py", line 184, in coerce
    return Stack(value, ctx["parent"], **stack_metadata)
  File "/home/ferumchrome/anaconda3/envs/pytorch15/lib/python3.7/site-packages/vot/stack/__init__.py", line 42, in __init__
    super().__init__(**kwargs)
  File "/home/ferumchrome/anaconda3/envs/pytorch15/lib/python3.7/site-packages/vot/utilities/attributes.py", line 193, in __init__
    super().__setattr__(aname, afield.coerce(avalue, {"parent": self}))
  File "/home/ferumchrome/anaconda3/envs/pytorch15/lib/python3.7/site-packages/vot/utilities/attributes.py", line 315, in coerce
    container[name] = self._contains.coerce(data, dict(key=name, **context))
  File "/home/ferumchrome/anaconda3/envs/pytorch15/lib/python3.7/site-packages/vot/utilities/attributes.py", line 358, in coerce
    return self._resolver(class_name, context, **{k: v for k, v in value.items() if not k == "type"})
  File "/home/ferumchrome/anaconda3/envs/pytorch15/lib/python3.7/site-packages/vot/stack/__init__.py", line 16, in experiment_resolver
    experiment_class = import_class(typename)
  File "/home/ferumchrome/anaconda3/envs/pytorch15/lib/python3.7/site-packages/vot/utilities/__init__.py", line 21, in import_class
    delimiter = classpath.rfind(".")
AttributeError: 'NoneType' object has no attribute 'rfind'

Can you provide some guidance on how to run vot analysis function?

**Comment by lukacu** [comment]
VOT2017 stack is really not supported at the moment, we have tried to finish the VOT2020 stuff first. Old stacks will eventually be tested, but the toolkit has changed significantly over the past months and we did not have time to constantly test and fix all stacks.

**Comment by lukacu** [comment]
Ok, I will mark this as bug and investigate it in the following days.

**Comment by lukacu** [comment]
Stack have been modified several times since this issue was opened. Is this still relevant?

**Comment by lukacu** [comment]
No response, closing.
