### ISSUE TITLE
vot evaluation 

### ISSUE THREAD

**Issue by agyurjin** [votchallenge/toolkit#17]
Hi,

I wanted to use vot-toolkit, but got some errors. First it was same as in the forum here:
https://groups.google.com/forum/#!topic/votchallenge-help/wUOVxJ16qyE

Later when I started to use dev, I started to get this error:

'Polygon' object has no attribute 'points'
Traceback (most recent call last):
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/utilities/cli.py", line 364, in main
    do_evaluate(args, logger)
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/utilities/cli.py", line 174, in do_evaluate
    run_experiment(experiment, tracker, workspace.dataset, config.force, config.persist)
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/experiment/__init__.py", line 130, in run_experiment
    experiment.execute(tracker, sequence, force=force, callback=progress)
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/experiment/multirun.py", line 123, in execute
    _, properties, elapsed = runtime.initialize(sequence.frame(frame), self._get_initialization(sequence, frame))
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/tracker/trax.py", line 396, in initialize
    return self._process.initialize(frame, region, tproperties)
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/tracker/trax.py", line 238, in initialize
    tregion = convert_region(region)
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/tracker/trax.py", line 85, in convert_region
    return TraxPolygon.create(region.points)
AttributeError: 'Polygon' object has no attribute 'points'
 NCCPython/baseline   |                                                                  |   0% [00:00<?]
Terminate

Can you help me to solve the problem? Thank you!
Armen

**Comment by lukacu** [comment]
This is a bug, I will fix it today. We have currently focused on VOT2020 and this means that only axis-aligned bounding boxes and masks were used, the polygon regions were not tested that much.

**Comment by lukacu** [comment]
I have committed a fix to dev branch, please test it and see if it works for you.

**Comment by agyurjin** [comment]
Thank you a lot. That works now. 
I wanted to use analysis and it gave some errors. --output argument doesn't exist, so I try without it and got following error.

Error during analysis ('vot.analysis.basic.FailureCount@da39a3ee5e6b4b0d3255bfef95601890afd80709', 'baseline', '8e4212e41c60223e6090840924a577c5eb583b61', '1da6147762229c6a8f0afd245ee18c63651ba90c')
None
Traceback (most recent call last):
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/analysis/processor.py", line 99, in __call__
    return self._analysis.join(self._experiment, self._trackers, self._sequences, self._results)
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/analysis/__init__.py", line 278, in join
    collapsed.append(self.collapse(tracker, sequences, partial))
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/analysis/basic.py", line 120, in collapse
    failures = failures + a
TypeError: unsupported operand type(s) for +: 'int' and 'tuple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/analysis/processor.py", line 384, in insert
    container[key] = future.result()
  File "/home/armen/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/armen/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/analysis/processor.py", line 275, in _future_done
    result = future.result()
  File "/home/armen/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/armen/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/analysis/processor.py", line 139, in _on_done
    self.set_result(future.result())
  File "/home/armen/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/armen/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/armen/miniconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/analysis/processor.py", line 101, in __call__
    raise AnalysisError(e, task=self._key)
vot.analysis.processor.AnalysisError: Error during analysis ('vot.analysis.basic.FailureCount@da39a3ee5e6b4b0d3255bfef95601890afd80709', 'baseline', '8e4212e41c60223e6090840924a577c5eb583b61', '1da6147762229c6a8f0afd245ee18c63651ba90c')
Waiting for 1 analysis tasks to finish
 Running analysis     |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100% [00:00<00:00]
'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/utilities/cli.py", line 366, in main
    do_analysis(args, logger)
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/utilities/cli.py", line 237, in do_analysis
    generate_document(config.format, workspace.report, trackers, workspace.dataset, results, storage)
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/document/__init__.py", line 348, in generate_document
    eresults[analysis] = [aresults[i] for i in order]
  File "/home/armen/miniconda3/lib/python3.7/site-packages/vot/document/__init__.py", line 348, in <listcomp>
    eresults[analysis] = [aresults[i] for i in order]
TypeError: 'NoneType' object is not subscriptable

**Comment by lukacu** [comment]
Likely outdated now, closing.
