### ISSUE TITLE
vot analysis error

### ISSUE THREAD

**Issue by frank-chan-ck** [votchallenge/toolkit#29]
I have obtained 120 data results (such as ants1.txt and ants1_time.txt) of the prdimp algorithm on the VOT2018 data set through other methods. After copying the result to /home/user/vot_workspace/results and using the command `vot analysis dimp --workspace /home/user/vot_workspace,` the following error appears. The generated analysis result is saved as an html format file. After opening it, you can find all the results are N/A. Please help to find out what went wrong?

Checking for new version
Unable to retrieve version information HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /votchallenge/vot-toolkit-python/raw/master/vot/version.py (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fda824249d0>, 'Connection to github.com timed out. (connect timeout=2)'))
 Loading dataset      |█████████████████████████████████████| 100% [00:00<00:00]
Loaded workspace in '/home/user/vot_workspace'
Scanning registry /home/user/vot_workspace/trackers.ini
Found 1 trackers
Found data for 1 trackers
Running analysis for 1 trackers
Setting default analysis processor for thread MainThread
Traversing experiment baseline
Traversing analysis vot.analysis.ar.AccuracyRobustness
Traversing analysis vot.analysis.basic.FailureCount
Error during analysis ('vot.analysis.ar.AccuracyRobustness@561c8413e5ff2b1b5a17b032824e1c099ac22d30', 'baseline', '33020f6cc72fa21288f33e5c97ff07721696580c', 'd380000eaa318e49fc3f459fbca9634dac591dbd')
Caused by an error in subtask: ('vot.analysis.ar.AccuracyRobustness@561c8413e5ff2b1b5a17b032824e1c099ac22d30', 'baseline', 'dimp', 'ants1')
None
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/pysot/lib/python3.7/site-packages/vot/analysis/processor.py", line 82, in __call__
    return self._analysis.subcompute(*self._arguments)
  File "/home/user/anaconda3/envs/pysot/lib/python3.7/site-packages/vot/analysis/ar.py", line 81, in subcompute
    raise MissingResultsException()
vot.analysis.MissingResultsException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/pysot/lib/python3.7/site-packages/vot/analysis/processor.py", line 124, in _on_result
    self._results[i] = future.result()
  File "/home/user/anaconda3/envs/pysot/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/user/anaconda3/envs/pysot/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/user/anaconda3/envs/pysot/lib/python3.7/site-packages/vot/analysis/processor.py", line 276, in _future_done
    result = future.result()
  File "/home/user/anaconda3/envs/pysot/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/user/anaconda3/envs/pysot/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/user/anaconda3/envs/pysot/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/user/anaconda3/envs/pysot/lib/python3.7/site-packages/vot/analysis/processor.py", line 84, in __call__
    raise AnalysisError(e, task=self._key)
vot.analysis.processor.AnalysisError: Error during analysis ('vot.analysis.ar.AccuracyRobustness@561c8413e5ff2b1b5a17b032824e1c099ac22d30', 'baseline', 'dimp', 'ants1')
......
......
......
KeyError: <AnalysisAggregator at 0x7fda71715710 state=finished raised AnalysisError>
Analysis successful, report available as 2021-03-01T00-18-31.335324

**Comment by yuyudiandian** [comment]
same error.Have you solved it?

**Comment by salcanmor** [comment]
@frank-chan-ck @lukacu @LearnByDoingXW @yuyudiandian

Hi guys, have you solved this issue? 
Can you please explain how you solved it ?

**Comment by lukacu** [comment]
No activity, closing the issue.
