### ISSUE TITLE
TypeError: 'CoerceContext' object is not subscriptable

### ISSUE THREAD

**Issue by xingpingdong** [votchallenge/toolkit#43]
when I try to evaluate the default tracker NCC and run the following command

`vot evaluate --workspace '/home/dxp/code/vot-test/workspace2' NCCPython
`
I got the following errors.

Traceback (most recent call last):
  File "/home/dxp/anaconda3/envs/siamban/lib/python3.7/site-packages/vot/utilities/cli.py", line 388, in main
    do_evaluate(args)
  File "/home/dxp/anaconda3/envs/siamban/lib/python3.7/site-packages/vot/utilities/cli.py", line 159, in do_evaluate
    workspace = Workspace.load(config.workspace)
  File "/home/dxp/anaconda3/envs/siamban/lib/python3.7/site-packages/vot/workspace/__init__.py", line 138, in load
    return Workspace(directory, **config)
  File "/home/dxp/anaconda3/envs/siamban/lib/python3.7/site-packages/vot/workspace/__init__.py", line 150, in __init__
    super().__init__(**kwargs)
  File "/home/dxp/anaconda3/envs/siamban/lib/python3.7/site-packages/attributee/__init__.py", line 262, in __init__
    value = afield.coerce(avalue, CoerceContext(parent=self))
  File "/home/dxp/anaconda3/envs/siamban/lib/python3.7/site-packages/attributee/containers.py", line 134, in coerce
    data = [self._contains.coerce(x, CoerceContext(parent=parent, key=i)) for i, x in enumerate(value)]
  File "/home/dxp/anaconda3/envs/siamban/lib/python3.7/site-packages/attributee/containers.py", line 134, in <listcomp>
    data = [self._contains.coerce(x, CoerceContext(parent=parent, key=i)) for i, x in enumerate(value)]
  File "/home/dxp/anaconda3/envs/siamban/lib/python3.7/site-packages/attributee/primitives.py", line 104, in coerce
    return self._transformer(to_string(value), ctx)
  File "/home/dxp/anaconda3/envs/siamban/lib/python3.7/site-packages/vot/workspace/__init__.py", line 54, in <lambda>
    registry = List(String(transformer=lambda x, ctx: normalize_path(x, ctx["parent"].directory)))
TypeError: 'CoerceContext' object is not subscriptable

It seems a bug in the code. Could you help me?

**Comment by lukacu** [comment]
Yes, it seems that there are a few issues because the newest attributee library version is used. You can try to downgrade the library version, probably to 0.1.3 .

**Comment by xingpingdong** [comment]
Thank you. I fixed it by setting attributtee==0.1.3.

**Comment by lukacu** [comment]
Well, it is not a fix, more of a workaround. I will reopen the issue and only close it once we fix it for the new version.

**Comment by tahiira** [comment]
> Yes, it seems that there are a few issues because the newest attributee library version is used. You can try to downgrade the library version, probably to 0.1.3 .

Hi,
I faced with this error, how can I downgrade vot-toolkit-python

**Comment by xingpingdong** [comment]
> 
Maybe you can try pip install attributtee==0.1.3

**Comment by xingpingdong** [comment]
> 

Maybe you can try pip install attributtee==0.1.3

**Comment by tahiira** [comment]
> > 
> 
> Maybe you can try pip install attributtee==0.1.3

Thank you, but the error didnt resolve.
I use python3.6 with cuda 11.

**Comment by xingpingdong** [comment]
Maybe you need to update your python. I used python 3.7

T.H ***@***.***>于2022年3月5日 周六11:19写道：
