### ISSUE TITLE
AttributeError: 'List' object has no attribute 'directory'

### ISSUE THREAD

**Issue by minggii** [votchallenge/toolkit#48]
Hi, I am getting this error related to attirubtee library:

```
'List' object has no attribute 'directory'
Traceback (most recent call last):                                                                                                     
  File "/home/minji/miniconda3/envs/slt/lib/python3.7/site-packages/vot/utilities/cli.py", line 388, in main                           
    do_evaluate(args)                                                                                                                  
  File "/home/minji/miniconda3/envs/slt/lib/python3.7/site-packages/vot/utilities/cli.py", line 165, in do_evaluate                    
    registry = Registry(workspace.registry + global_registry, root=config.workspace)                                                   
  File "/home/minji/miniconda3/envs/slt/lib/python3.7/site-packages/attributee/containers.py", line 41, in __add__                     
    self.append(item)                                                                                                                  
  File "/home/minji/miniconda3/envs/slt/lib/python3.7/site-packages/attributee/containers.py", line 38, in append                      
    self._data.append(self._type.coerce(item, ctx))                                                                                    
  File "/home/minji/miniconda3/envs/slt/lib/python3.7/site-packages/attributee/primitives.py", line 104, in coerce                     
    return self._transformer(to_string(value), ctx)                                                                                    
  File "/home/minji/miniconda3/envs/slt/lib/python3.7/site-packages/vot/workspace/__init__.py", line 56, in <lambda>                   
    registry = List(String(transformer=lambda x, ctx: normalize_path(x, ctx.parent.directory)))                                        
AttributeError: 'List' object has no attribute 'directory'
```

My command was:
```
vot evaluate --workspace <workspace_path> <tracker_name>
```

I have used the toolkit several times before, but I'm getting this error for the first time. I think this might be related to the current code update.

Thanks :)

**Comment by franktpmvu** [comment]
it's seems like attributee new version have some mismatch 
you can try :
pip install attributee==0.1.5 after install vottoolkit 
it's work for me

**Comment by minggii** [comment]
@franktpmvu This also worked for me. Thanks!

**Comment by lukacu** [comment]
This should be fixed in the new version.
