### ISSUE TITLE
VOT 2023 error

### ISSUE THREAD

**Issue by imadtoubal** [votchallenge/toolkit#73]
Hi, I have been trying to follow [these instructions to download the VOT2023](https://www.votchallenge.net/vots2023/participation.html). But it seems there might be an error with the package?

Below is the full error stack.
```
$ vot initialize vots2023
A newer version of the VOT toolkit is available (0.6.1), please update.
Unable to read JSON file Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/site-packages/vot/utilities/net.py", line 53, in download_json
    return requests.get(url).json()
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/site-packages/vot/utilities/cli.py", line 403, in main
    do_workspace(args)
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/site-packages/vot/utilities/cli.py", line 168, in do_workspace
    Workspace.initialize(config.workspace, default_config, download=not config.nodownload)
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/site-packages/vot/workspace/__init__.py", line 103, in initialize
    Workspace.download_dataset(dataset, dataset_directory)
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/site-packages/vot/workspace/__init__.py", line 118, in download_dataset
    download_dataset(dataset, directory)
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/site-packages/vot/dataset/__init__.py", line 584, in download_dataset
    download_dataset_meta(url, path)
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/site-packages/vot/dataset/vot.py", line 169, in download_dataset_meta
    meta = download_json(url)
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/site-packages/vot/utilities/net.py", line 55, in download_json
    raise NetworkException("Unable to read JSON file {}".format(e))
vot.utilities.net.NetworkException: Unable to read JSON file Expecting value: line 1 column 1 (char 0)
```

**Comment by Zhangyong-Tang** [comment]
Does the 'vot initailize vots2023' can be processed successfully?
The test dataset can not downloaded right now.
