### ISSUE TITLE
Can't download vots2023

### ISSUE THREAD

**Issue by ngoctuan1** [votchallenge/toolkit#75]
Hi u, I have installed vote-toolkit 0.6.1. But I can't load the VOT 2023 dataset. It fails when it has reached 16%.
`Traceback (most recent call last):
  File "/home/server1-ailab/miniconda3/envs/tuan_toolkit/lib/python3.8/site-packages/vot/utilities/cli.py", line 409, in main
    do_workspace(args)
  File "/home/server1-ailab/miniconda3/envs/tuan_toolkit/lib/python3.8/site-packages/vot/utilities/cli.py", line 168, in do_workspace
    Workspace.initialize(config.workspace, default_config, download=not config.nodownload)
  File "/home/server1-ailab/miniconda3/envs/tuan_toolkit/lib/python3.8/site-packages/vot/workspace/__init__.py", line 103, in initialize
    Workspace.download_dataset(dataset, dataset_directory)
  File "/home/server1-ailab/miniconda3/envs/tuan_toolkit/lib/python3.8/site-packages/vot/workspace/__init__.py", line 118, in download_dataset
    download_dataset(dataset, directory)
  File "/home/server1-ailab/miniconda3/envs/tuan_toolkit/lib/python3.8/site-packages/vot/dataset/__init__.py", line 584, in download_dataset
    download_dataset_meta(url, path)
  File "/home/server1-ailab/miniconda3/envs/tuan_toolkit/lib/python3.8/site-packages/vot/dataset/vot.py", line 200, in download_dataset_meta
    raise DatasetException("Unable do download channel bundle")
vot.dataset.DatasetException: Unable do download channel bundle`

**Comment by lukacu** [comment]
Hi, we have checked again the downloading process and it completes fine. Does it fail at the same sequence every time?

**Comment by ngoctuan1** [comment]
I uninstalled vot-toolkit and reinstalled it. It's version 0.6.1. And I
re-downloaded 'vot initialize vots2023 --workspace data_2023'. When the
process reaches 16%, there will be an error[image: image.png]
[image: image.png]
[image: image.png]

Vào CN, 14 thg 5, 2023 vào lúc 19:36 Luka Čehovin Zajc <
***@***.***> đã viết:

**Comment by franktpmvu** [comment]
same stop in 16%, it says 

```shell
Downloading sequence dataset "VOTS2023 Challenge" with 144 sequences.
 Downloading          |███████████████▍                                                                                 |  16% [11:59<1:03:05]
File is not a zip file
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/vot/utilities/cli.py", line 409, in main
    do_workspace(args)
  File "/opt/conda/lib/python3.7/site-packages/vot/utilities/cli.py", line 168, in do_workspace
    Workspace.initialize(config.workspace, default_config, download=not config.nodownload)
  File "/opt/conda/lib/python3.7/site-packages/vot/workspace/__init__.py", line 103, in initialize
    Workspace.download_dataset(dataset, dataset_directory)
  File "/opt/conda/lib/python3.7/site-packages/vot/workspace/__init__.py", line 118, in download_dataset
    download_dataset(dataset, directory)
  File "/opt/conda/lib/python3.7/site-packages/vot/dataset/__init__.py", line 584, in download_dataset
    download_dataset_meta(url, path)
  File "/opt/conda/lib/python3.7/site-packages/vot/dataset/vot.py", line 198, in download_dataset_meta
    download_uncompress(channel_url, channel_directory)
  File "/opt/conda/lib/python3.7/site-packages/vot/utilities/net.py", line 129, in download_uncompress
    extract_files(tmp_file, path)
  File "/opt/conda/lib/python3.7/site-packages/vot/utilities/__init__.py", line 169, in extract_files
    with ZipFile(file=archive) as zip_file:
  File "/opt/conda/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/opt/conda/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by lukacu** [comment]
Ok, so the carchase sequence is apparently quite large, the largest in the dataset. It did not cause problems for us when testing, but it may be that the chance of getting an error is much higher. We are investigating how to improve the download, expect a solution or at least a bypass soon (today).

**Comment by JornyWan** [comment]
> We have released version 0.6.2 of the toolkit that should improve the download process, try it out and report back.

thank you for your fast update, i tried to vot initialize but when it download at 13%, there is an error:
Downloading sequence dataset "VOTS2023 Challenge" with 144 sequences (total 26.0GiB).
 Downloading          |████████▊                                                          |  13% [22:16<1:30:55]
 Error when downloading file, trying to resume download
 Downloading          |█████████▎                                                         |  14% [31:54<7:01:48]

it seems that the download could continue but i'm worried about that there might be some file lost after finish the download

**Comment by JornyWan** [comment]
And I would like to know that the results I get when I evaluate the tracker with python_ncc in your integretion after using my vots2023 dataset earlier are empty: results = []
"results": {
    "baseline": {
      "parameters": {
        "realtime": null,
        "noise": null,
        "inject": null,
        "transformers": [],
        "analyses": [],
        "repetitions": 1,
        "early_stop": true,
        "multiobject": true
      },
      "type": "vot.experiment.multirun.UnsupervisedExperiment",
      "results": []
    }
  }

and only the json file can output the data contents and rusults above, or if the output is an html file, it can't output result:
VOT report
Toolkit version: 0.6.1
Created: 2023-05-16T22:08:17.203861

**Comment by lukacu** [comment]
We are mixing two things now and it is not a good thing in case of issue discussion. So the dataset download is now trying to resume downloads, files are large and connections break. If the download fails, it will still try to download the dataset again before running the tracker and it will skip sequences that are already downloaded.

The other issue is regarding results: please read participation instructions, this year we are running the challenge without public groundtruth, you have to submit results to our server (URL will be available) and you get back the scores. This means that you cannot really run analysis locally.
