### ISSUE TITLE
missing uid when downloading vots2023 challenge dataset

### ISSUE THREAD

**Issue by RobotVisionTsai** [votchallenge/toolkit#89]
Dear all,

I have updated the vot-toolkit to the newest version 0.6.3 and try to initialize the vots2023 workspace.
However, I encounter the following error about uid in the cli.py utility:

rvl224@96bb413952ec:/workspace/shared/vots23-workspace$ vot initialize vots2023
Downloading sequence dataset "VOTS2023 Challenge" with 144 sequences (total 26.0GiB).
 Downloading          |                                                                                                                                                                   |   0% [00:00<?]
'uid'
Traceback (most recent call last):
  File "/home/rvl224/.local/lib/python3.7/site-packages/vot/utilities/cli.py", line 442, in main
    do_workspace(args)
  File "/home/rvl224/.local/lib/python3.7/site-packages/vot/utilities/cli.py", line 191, in do_workspace
    Workspace.initialize(config.workspace, default_config, download=not config.nodownload)
  File "/home/rvl224/.local/lib/python3.7/site-packages/vot/workspace/__init__.py", line 120, in initialize
    Workspace.download_dataset(dataset, dataset_directory)
  File "/home/rvl224/.local/lib/python3.7/site-packages/vot/workspace/__init__.py", line 135, in download_dataset
    download_dataset(dataset, directory)
  File "/home/rvl224/.local/lib/python3.7/site-packages/vot/dataset/__init__.py", line 597, in download_dataset
    download_dataset_meta(url, path)
  File "/home/rvl224/.local/lib/python3.7/site-packages/vot/dataset/vot.py", line 205, in download_dataset_meta
    if refdata["uid"] == sequence["annotations"]["uid"]:
KeyError: 'uid'

Does someone suggest how to fix this issue?
Thanks a lot!

**Comment by lukacu** [comment]
This is kind of strange, did you have the dataset partially downloaded before upgrading the toolkit? Because we have introduced this check in 0.6.3 to support partial downloads and skip sequences that are already downloaded. I will make this check more robust, but it should work if entire workspace is initialized with 0.6.3.

**Comment by RobotVisionTsai** [comment]
Thank you for your answer, Lukacu.
I did have some previously downloaded sequences in the workspace folder.
After cleaning the folder, the workspace was initialized successfully. 
Thanks a lot!
