### ISSUE TITLE
Variable self._runtime referenced before initialization in vot/tracker/__init__.py

### ISSUE THREAD

**Issue by imadtoubal** [votchallenge/toolkit#91]
Looks like the member variable `self._runtime` is referenced before being initialized in [`vot/tracker/__init__.py` line 829](https://github.com/votchallenge/toolkit/blob/410c41f2cc35435f25083d6710bcfe478874d972/vot/tracker/__init__.py#L829
) resulting in the error:

```
Traceback (most recent call last):
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/site-packages/vot/utilities/cli.py", line 412, in main
    do_evaluate(args)
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/site-packages/vot/utilities/cli.py", line 200, in do_evaluate
    run_experiment(experiment, tracker, workspace.dataset, config.force, config.persist)
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/site-packages/vot/experiment/__init__.py", line 201, in run_experiment
    experiment.execute(tracker, sequence, force=force, callback=progress)
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/site-packages/vot/experiment/multirun.py", line 99, in execute
    with self._get_runtime(tracker, sequence, self._multiobject) as runtime:
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/site-packages/vot/experiment/__init__.py", line 109, in _get_runtime
    runtime = MultiObjectTrackerRuntime(runtime)
  File "/usr/mvl2/itdfh/anaconda3/envs/vot/lib/python3.10/site-packages/vot/tracker/__init__.py", line 555, in __init__
    if self._runtime.multiobject:
AttributeError: 'MultiObjectTrackerRuntime' object has no attribute '_runtime'
```

Changing this [line 829](https://github.com/votchallenge/toolkit/blob/410c41f2cc35435f25083d6710bcfe478874d972/vot/tracker/__init__.py#L829
) from:
```
        if self._runtime.multiobject:
```
to:
```
        if runtime:
```

solves the issue.

Have there been any successful uses of a multi-object tracker using this toolkit? Can I see some examples?

**Comment by lukacu** [comment]
Multi object wrapper does not really work at the moment. It is also not a good idea unless your tracker has very low resource requirements (no GPUs). We have some examples how to make your tracker truly multi objec in a separate repository (integrations).
